// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLYmLgwtc1qrA-X80_PrbIzybSTe--mM',
    appId: '1:159567769954:web:4fb772d3faf84d6149bc3b',
    messagingSenderId: '159567769954',
    projectId: 'bibliospace-app',
    authDomain: 'bibliospace-app.firebaseapp.com',
    storageBucket: 'bibliospace-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtJu7zjjt3vRw9o0bULinim1smeWo9gc',
    appId: '1:159567769954:android:fdf20a143d20c89649bc3b',
    messagingSenderId: '159567769954',
    projectId: 'bibliospace-app',
    storageBucket: 'bibliospace-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44aJpRGX1QuN5HVuONqY2OtCDSbL9wH8',
    appId: '1:159567769954:ios:9e63ffc1e24f458749bc3b',
    messagingSenderId: '159567769954',
    projectId: 'bibliospace-app',
    storageBucket: 'bibliospace-app.firebasestorage.app',
    iosBundleId: 'com.example.bibliospace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44aJpRGX1QuN5HVuONqY2OtCDSbL9wH8',
    appId: '1:159567769954:ios:9e63ffc1e24f458749bc3b',
    messagingSenderId: '159567769954',
    projectId: 'bibliospace-app',
    storageBucket: 'bibliospace-app.firebasestorage.app',
    iosBundleId: 'com.example.bibliospace',
  );
}
